data = {
    # https://github.com/Delitefully/DiscordLists/blob/master/domains.md
    "dis.gd",
    "discord.co",
    "discord.com",
    "discord.design",
    "discord.dev",
    "discord.gg",
    "discord.gift",
    "discord.gifts",
    "discord.media",
    "discord.new",
    "discord.store",
    "discord.tools",
    "discordapp.com",
    "discordapp.net",
    "discordmerch.net",
    "discordpartygames.com",
    "discord-activities.com",
    "discordactivities.com",
    "discordsays.com",
    "discordstatus.com",
    "discordapp.io",
    "discordcdn.com",
    # other discord related domains
    "discordpy.readthedocs.io",
    "disboard.org",
    "disboard.dev",
    # other domains used in phishing messages
    "bit.do",
    "bit.ly",
    "clck.ru",
    "cutt.ly",
    "gg.gg",
    "github.com",
    "google.com",
    "is.gd",
    "taplink.cc",
    "tinyurl.com",
    "transfer.sh",
    "twitter.com",
    "youtu.be",
    "youtube.com",
    "pixiv.net",
}
