# flake8: noqa E501
data = {
    "deueloper",  # developers
    "partners",  # partners
    "exam",  # exam
    "euents",  # events
    "deubot",  # devbot
    "mod",  # mod
    "support",  # support
    "intents",  # intents
    "api",  # api
    "partner",  # partner
    "message",  # message
    "messages",  # messages
    "moderator",  # moderator
    "academy",  # academy
    "deuelopers",  # developers
    "hypesouad",  # hypesquad
    "hype",  # hype
    "souad",  # squad
    "moderators",  # moderators
    "discord",  # discord
    "moderation",  # moderation
    "testers",  # testers
    "staff",  # staff
    "system",  # system
    "modmail",  # modmail
    "dbug",  # dbug
    "box",  # box
    "mail",  # mail
    "apply",  # apply
    "beta",  # beta
    "application",  # application
    "team",  # team
}
